project/app/urls.py
from django.urls import path

from . import views


app_name = 'app'
urlpatterns = [
    # PRODUCTS
    path('products/', views.ProductListView.as_view(), name='product-list'),
    path('products/report/', views.ProductReportView.as_view(), name='product-report'),
    path('products/create/', views.ProductCreateView.as_view(), name='product-create'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('products/<int:pk>/update/', views.ProductUpdateView.as_view(), name='product-update'), 
    path('products/<int:pk>/delete/', views.ProductDeleteView.as_view(), name='product-delete'),

    path('products/wholesalers/', views.WholeSalerListView.as_view(), name='wholesaler-list'),
    path('products/wholesalers/report/', views.WholesalerReportView.as_view(), name='wholesaler-report'),
    path('products/wholesalers/create/', views.WholesalerCreateView.as_view(), name='wholesaler-create'),
    path('products/wholesalers/<int:pk>/', views.WholesalerDetailView.as_view(), name='wholesaler-detail'),
    path('products/wholesalers/<int:pk>/update/', views.WholesalerUpdateView.as_view(), name='wholesaler-update'),
    path('products/wholesalers/<int:pk>/delete/', views.WholesalerDeleteView.as_view(), name='wholesaler-delete'),

    path('products/producers/', views.ProducerListView.as_view(), name='producer-list'),
    path('products/producers/report/', views.ProducerReportView.as_view(), name='producer-report'),
    path('products/producers/create/', views.ProducerCreateView.as_view(), name='producer-create'),
    path('products/producers/<int:pk>/', views.ProducerDetailView.as_view(), name='producer-detail'),
    path('products/producers/<int:pk>/update/', views.ProducerUpdateView.as_view(), name='producer-update'),
    path('products/producers/<int:pk>/delete/', views.ProducerDeleteView.as_view(), name='producer-delete'),

    path('products/categories/', views.CategoryListView.as_view(), name='category-list'),
    path('products/categories/report/', views.CategoryReportView.as_view(), name='category-report'),
    path('products/categories/create/', views.CategoryCreateView.as_view(), name='category-create'),
    path('products/categories/<int:pk>/', views.CategoryDetailView.as_view(), name='category-detail'),
    path('products/categories/<int:pk>/update/', views.CategoryUpdateView.as_view(), name='category-update'),
    path('products/categories/<int:pk>/delete/', views.CategoryDeleteView.as_view(), name='category-delete'),

    path('products/delivered-items/', views.DeliveredItemsListView.as_view(), name='delivered-items-list'),
    path('products/delivered-items/report/', views.DeliveredItemsReportView.as_view(), name='delivered-items-report'),
    path('products/delivered-items/create/', views.DeliveredItemsCreateView.as_view(), name='delivered-items-create'),
    path('products/delivered-items/<int:pk>/', views.DeliveredItemsDetailView.as_view(), name='delivered-items-detail'),
    path('products/delivered-items/<int:pk>/update/', views.DeliveredItemsUpdateView.as_view(), name='delivered-items-update'),
    path('products/delivered-items/<int:pk>/delete/', views.DeliveredItemsDeleteView.as_view(), name='delivered-items-delete'),

    # ORDERS
    path('orders/', views.OrderListView.as_view(), name='order-list'),
    path('orders/report/', views.OrderReportView.as_view(), name='order-report'),
    path('orders/<int:pk>/', views.OrderDetailView.as_view(), name='order-detail'),
    path('orders/<int:pk>/update/', views.OrderUpdateView.as_view(), name='order-update'),
    path('orders/<int:pk>/delete/', views.OrderDeleteView.as_view(), name='order-delete'),
    path('orders/<int:pk>/add/', views.AddItemView.as_view(), name='order-additem'),
    path('orders/create/', views.OrderCreateView.as_view(), name='order-create'),

    path('orders/addresses/report/', views.AddressReportView.as_view(), name='address-report'),
    path('orders/addresses/<int:pk>/', views.AddressDetailView.as_view(), name='address-detail'),
    path('orders/addresses/<int:pk>/update/', views.AddressUpdateView.as_view(), name='address-update'),
    path('orders/addresses/<int:pk>/delete/', views.AddressDeleteView.as_view(), name='address-delete'),
    path('orders/addresses/create/', views.AddressCreateView.as_view(), name='address-create'),

    path('orders/items/', views.ItemInOrderListView.as_view(), name='items-list'),
    path('orders/items/report/', views.ItemInOrderReportView.as_view(), name='items-report'),
    path('orders/items/<int:pk>/', views.ItemInOrderDetailView.as_view(), name='items-detail'),
    path('orders/items/<int:pk>/update/', views.ItemInOrderUpdateView.as_view(), name='items-update'),
    path('orders/items/<int:pk>/delete/', views.ItemInOrderDeleteView.as_view(), name='items-delete'),
    path('orders/items/create/', views.ItemInOrderCreateView.as_view(), name='items-create'),

    path('orders/payments/', views.PaymentListView.as_view(), name='payment-list'),
    path('orders/payments/report/', views.PaymentReportView.as_view(), name='payment-report'),
    path('orders/payments/<int:pk>/', views.PaymentDetailView.as_view(), name='payment-detail'),
    path('orders/payments/<int:pk>/update/', views.PaymentUpdateView.as_view(), name='payment-update'),
    path('orders/payments/<int:pk>/delete/', views.PaymentDeleteView.as_view(), name='payment-delete'),
    path('orders/payments/create/', views.PaymentCreateView.as_view(), name='payment-create'),

    # EMPLOYEES
    path('employees/', views.EmployeeListView.as_view(), name='employee-list'),
    path('employees/report/', views.EmployeeReportView.as_view(), name='employee-report'),
    path('employees/<int:pk>/', views.EmployeeDetailView.as_view(), name='employee-detail'),
    path('employees/<int:pk>/update/', views.EmployeeUpdateView.as_view(), name='employee-update'),
    path('employees/<int:pk>/delete/', views.EmployeeDeleteView.as_view(), name='employee-delete'),
    path('employees/create/', views.EmployeeCreateView.as_view(), name='employee-create'),

    path('employees/positions/', views.PositionListView.as_view(), name='position-list'),
    path('employees/positions/report/', views.PositionReportView.as_view(), name='position-report'),
    path('employees/positions/create/', views.PositionCreateView.as_view(), name='position-create'),
    path('employees/positions/<int:pk>/', views.PositionDetailView.as_view(), name='position-detail'),
    path('employees/positions/<int:pk>/update/', views.PositionUpdateView.as_view(), name='position-update'),
    path('employees/positions/<int:pk>/delete/', views.PositionDeleteView.as_view(), name='position-delete'),

    # CLIENTS
    path('clients/', views.ClientListView.as_view(), name='client-list'),
    path('clients/report/', views.ClientReportView.as_view(), name='client-report'),
    path('clients/<int:pk>/', views.ClientDetailView.as_view(), name='client-detail'),
    path('clients/<int:pk>/update/', views.ClientUpdateView.as_view(), name='client-update'),
    path('clients/<int:pk>/delete/', views.ClientDeleteView.as_view(), name='client-delete'),
    path('clients/create/', views.ClientCreateView.as_view(), name='client-create'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import include, path

from .settings import DEBUG
from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='homepage'),
    path('about/', views.AboutPageView.as_view(), name='aboutpage'),
    path('report/', views.ReportPageView.as_view(), name='reportpage'),
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
]

if not DEBUG:
    handler400 = 'project.views.error404Handler'
    handler404 = 'project.views.error404Handler'
    handler500 = 'project.views.error500Handler'

project/app/templates/app/address_detail.html
{% extends "base.html" %}

{% block content %}
    <div style="width: 90%; margin-left: 5%; font-size:1.2rem;">
        <div class="card" style="width: 80%; margin-left: 10%;">
            <div class="card-header">
              {% if orders %}
                <span class="d-inline-block" tabindex="0" data-toggle="tooltip" title="Disabled: First, remove the orders below" style="float: right; margin-top: 1%;">
                  <a href="#" class="btn btn-secondary" ><span class="fa fa-trash"></span></a>
                </span>
              {% else %}
                <a href="delete/" class="btn btn-danger" style="float: right; margin-top: 1%;"><span class="fa fa-trash"></span></a>
              {% endif %}
              
              <a href="update/" class="btn btn-primary" style="float: right; margin-right: 2%; margin-top: 1%;"><span class="fa fa-pencil"></span></a>
              <h1 class="card-title">Address</h1>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><strong>Street:</strong> {{ object.ulica }} {{object.nr_ulicy}}</li>
              <li class="list-group-item"><strong>City:</strong> {{ object.miasto }}</li>
              <li class="list-group-item"><strong>Post code:</strong> {{ object.kod_pocztowy }}</li>
              <li class="list-group-item"><strong>Country:</strong> {{ object.kraj }}</li>
            </ul>
        </div>
        <br>
        {% if orders %}
        <br>
        <div class="card" style="width: 80%; margin-left: 10%;">
          <div class="card-header">
            <h1 class="card-title" style="float: left;">Connected Orders</h1>
          </div>
          <ul class="list-group list-group-flush">
            {% for order in orders %}
              <a class="list-group-item list-group-item-action" href="{% url 'app:order-detail' order.numer %}">{{ order }}</a>
            {% endfor %}
          </ul>
        </div>
        {% endif %}
    </div>
{% endblock %}

project/app/templates/app/address_report.html
{% extends "base.html" %}

{% block content%}

  <div style="width: 100%; margin-left: 2%;">
    {% include "report_list.html" %}
    <div style="width: 75%; margin-left: 21%;">
        <h2>Addresses</h2>
        <p class="lead">Edit address by clicking on it.</p>
        <br>
        <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Street</th>
                <th scope="col">Number</th>
                <th scope="col">Post Code</th>
                <th scope="col">City</th>
                <th scope="col">Country</th>
              </tr>
            </thead>
            <tbody>
              {% for obj in object_list %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td><a class="list-group-item-action" href="{% url 'app:address-detail' obj.id %}">{{ obj.ulica }}</a></td>
                  <td><a class="list-group-item-action" href="{% url 'app:address-detail' obj.id %}">{{ obj.nr_ulicy }}</a></td>
                  <td><a class="list-group-item-action" href="{% url 'app:address-detail' obj.id %}">{{ obj.kod_pocztowy }}</a></td>
                  <td><a class="list-group-item-action" href="{% url 'app:address-detail' obj.id %}">{{ obj.miasto }}</a></td>
                  <td><a class="list-group-item-action" href="{% url 'app:address-detail' obj.id %}">{{ obj.kraj }}</a></td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
    </div>
  </div>

{% endblock %}

project/app/templates/app/category_report.html
{% extends "base.html" %}

{% block content%}

  <div style="width: 100%; margin-left: 2%;">
    {% include "report_list.html" %}
    <div style="width: 75%; margin-left: 21%;">
        <h2>Categories</h2>
        <br>
        <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Overcategory</th>
              </tr>
            </thead>
            <tbody>
              {% for obj in object_list %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{ obj.nazwa }}</td>
                  <td>{{ obj.id_nadkategorii }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
    </div>
  </div>

{% endblock %}

project/app/templates/app/client_detail.html
{% extends "base.html" %}

{% block content %}
    <div style="width: 90%; margin-left: 5%; font-size:1.2rem;">
        <div class="card" style="width: 80%; margin-left: 10%;">
            <div class="card-header">
              {% if orders %}
                <span class="d-inline-block" tabindex="0" data-toggle="tooltip" title="Disabled: First, remove the orders below" style="float: right; margin-top: 1%;">
                  <a href="#" class="btn btn-secondary" ><span class="fa fa-trash"></span></a>
                </span>
              {% else %}
                <a href="delete/" class="btn btn-danger" style="float: right; margin-top: 1%;"><span class="fa fa-trash"></span></a>
              {% endif %}
              <a href="update/" class="btn btn-primary" style="float: right; margin-right: 2%; margin-top: 1%;"><span class="fa fa-pencil"></span></a>
              <h1 class="card-title">{{ object }}</h1>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><strong>Name:</strong> {{ object.imie }}</li>
              <li class="list-group-item"><strong>Surname:</strong> {{ object.nazwisko }}</li>
              <li class="list-group-item"><strong>Phone:</strong> {{ object.nr_telefonu }}</li>
              <li class="list-group-item"><strong>Email:</strong> {{ object.email }}</li>
              <li class="list-group-item"><strong>Discount code:</strong> {{ object.kod_karty_rabatowej }}</li>
            </ul>
        </div>

        {% if orders %}
        <br>
        <div class="card" style="width: 80%; margin-left: 10%;">
          <div class="card-header">
            <h1 class="card-title">Connected Orders</h1>
          </div>
          <ul class="list-group list-group-flush">
            {% for order in orders %}
              <a class="list-group-item list-group-item-action" href="{% url 'app:order-detail' order.numer %}">{{ order }}</a>
            {% endfor %}
          </ul>
        </div>
        {% endif %}
        <br>
    </div>
{% endblock %}

project/app/templates/app/client_report.html
{% extends "base.html" %}

{% block content%}

  <div style="width: 100%; margin-left: 2%;">
    {% include "report_list.html" %}
    <div style="width: 75%; margin-left: 21%;">
        <h2>Clients</h2>
        <br>
        <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Surname</th>
                <th scope="col">Phone Number</th>
                <th scope="col">Email</th>
                <th scope="col">Discount card code</th>
              </tr>
            </thead>
            <tbody>
              {% for obj in object_list %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{ obj.imie }}</td>
                  <td>{{ obj.nazwisko }}</td>
                  <td>{{ obj.nr_telefonu }}</td>
                  <td>{{ obj.email }}</td>
                  <td>{{ obj.kod_karty_rabatowej }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
    </div>
  </div>

{% endblock %}

project/app/templates/app/clients_list.html
{% extends "base.html" %}

{% block content%}
    <div style="width: 90%; margin-left: 5%;">
        <div class="position-fixed card" style="width: 15%;">
            <div class="card-header">
              Select topic
            </div>
            <ul class="list-group list-group-flush">
                <a class="list-group-item list-group-item-action" href="{% url 'app:client-list' %}">Clients</a>
            </ul>
        </div>

        {% include "list.html" %}
        
    </div>
{% endblock %}

project/app/templates/app/delivereditems_detail.html
{% extends "base.html" %}

{% block content %}
    <div style="width: 90%; margin-left: 5%; font-size:1.2rem;">
        <div class="card" style="width: 80%; margin-left: 10%;">
            <div class="card-header">
              {% if items %}
                <span class="d-inline-block" tabindex="0" data-toggle="tooltip" title="Disabled: First, remove the items in orders below" style="float: right; margin-top: 1%;">
                  <a href="#" class="btn btn-secondary" ><span class="fa fa-trash"></span></a>
                </span>
              {% else %}
                <a href="delete/" class="btn btn-danger" style="float: right; margin-top: 1%;"><span class="fa fa-trash"></span></a>
              {% endif %}
              <a href="update/" class="btn btn-primary" style="float: right; margin-right: 2%; margin-top: 1%;"><span class="fa fa-pencil"></span></a>
              <h1 class="card-title">{{ object }}</h1>
            </div>
            <ul class="list-group list-group-flush">
                {% if object.id_produktu %}
                  <a class="list-group-item list-group-item-action" href="{% url 'app:product-detail' object.id_produktu.id %}"><strong>Product:</strong> {{ object.id_produktu }}</a>
                {% else %}
                  <li class="list-group-item"><strong>Product:</strong> Deleted</li>
                {% endif %}
                <li class="list-group-item"><strong>Date:</strong> {{ object.data }}</li>
                <li class="list-group-item"><strong>Quantity:</strong> {{ object.ilosc }}</li>
                <li class="list-group-item"><strong>Unit purchase price:</strong> {{ object.cena_jednostkowa_zakupu }}PLN</li>
                <li class="list-group-item"><strong>Unit selling price:</strong> {{ object.cena_jednostkowa_sprzedazy }}PLN</li>
                {% if object.id_hurtownii %}
                  <a class="list-group-item list-group-item-action" href="{% url 'app:wholesaler-detail' object.id_hurtownii.id %}"><strong>Wholesaler:</strong> {{ object.id_hurtownii }}</a>
                {% else %}
                  <li class="list-group-item"><strong>Wholesaler:</strong> Deleted</li>
                {% endif %}
            </ul>
        </div>

        {% if items %}
          <br>
          <div class="card" style="width: 80%; margin-left: 10%;">
            <div class="card-header">
              <h1 class="card-title">Connected Items in orders</h1>
            </div>
            <ul class="list-group list-group-flush">
              {% for item in items %}
                <a class="list-group-item list-group-item-action" href="{% url 'app:items-detail' item.id %}">{{ item }}</a>
              {% endfor %}
            </ul>
          </div>
        {% endif %}
        <br>
      </div>
{% endblock %}

project/app/templates/app/employee_detail.html
{% extends "base.html" %}

{% block content %}
    <div style="width: 90%; margin-left: 5%; font-size:1.2rem;">
        <div class="card" style="width: 80%; margin-left: 10%;">
            <div class="card-header">
              {% if orders %}
                <span class="d-inline-block" tabindex="0" data-toggle="tooltip" title="Disabled: First, remove the orders below" style="float: right; margin-top: 1%;">
                  <a href="#" class="btn btn-secondary" ><span class="fa fa-trash"></span></a>
                </span>
              {% else %}
                <a href="delete/" class="btn btn-danger" style="float: right; margin-top: 1%;"><span class="fa fa-trash"></span></a>
              {% endif %}
              
              <a href="update/" class="btn btn-primary" style="float: right; margin-right: 2%; margin-top: 1%;"><span class="fa fa-pencil"></span></a>
              <form method="post">{% csrf_token %}
                <button type="submit" name='procedure' value='1' class="btn btn-success" style="float: right; margin-right: 2%; margin-top: 1%;">+100PLN</button>
              </form>
              <h1 class="card-title">{{ object }}</h1>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><strong>Name:</strong> {{ object.imie }}</li>
              <li class="list-group-item"><strong>Surname:</strong> {{ object.nazwisko }}</li>
              <li class="list-group-item"><strong>Phone:</strong> {{ object.nr_telefonu }}</li>
              <li class="list-group-item"><strong>Email:</strong> {{ object.email }}</li>
              <li class="list-group-item"><strong>Salary:</strong> {{ object.placa }}PLN</li>
              <li class="list-group-item"><strong>Hours per week:</strong> {{ object.ilosc_godzin_tyg }}</li>
              {% if object.id_stanowiska %}
                <a class="list-group-item list-group-item-action" href="{% url 'app:position-detail' object.id_stanowiska.id %}"><strong>Position:</strong> {{ object.id_stanowiska }}</a>
              {% else %}
                <li class="list-group-item"><strong>Position:</strong> Deleted</li>
              {% endif %}
            </ul>
        </div>

        {% if orders %}
        <br>
        <div class="card" style="width: 80%; margin-left: 10%;">
          <div class="card-header">
            <h1 class="card-title">Connected Orders</h1>
          </div>
          <ul class="list-group list-group-flush">
            {% for order in orders %}
              <a class="list-group-item list-group-item-action" href="{% url 'app:order-detail' order.numer %}">{{ order }}</a>
            {% endfor %}
          </ul>
        </div>
        {% endif %}
        <br>
    </div>
{% endblock %}

project/app/templates/app/item_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="jumbotron" style="width: 70%; margin-left: 15%; font-size:1.2rem;">
        <h3 class="display-4">Let's create something new...</h3>
        <br>
        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <br>
            <input class='btn btn-secondary btn-lg' name="first" type="submit" value="Add another one..." style="width: 100%;">
            <br><br>
            <input class='btn btn-primary btn-lg' type="submit" value="That's all!" style="width: 100%;">
        </form>
    </div>
{% endblock %}

project/app/templates/app/iteminorder_detail.html
{% extends "base.html" %}

{% block content %}
    <div style="width: 90%; margin-left: 5%; font-size:1.2rem;">
        <div class="card" style="width: 80%; margin-left: 10%;">
            <div class="card-header">
              <a href="delete/" class="btn btn-danger" style="float: right; margin-top: 1%;"><span class="fa fa-trash"></span></a>
              <a href="update/" class="btn btn-primary" style="float: right; margin-right: 2%; margin-top: 1%;"><span class="fa fa-pencil"></span></a>
              <h1 class="card-title">{{ object }}</h1>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><strong>Quantity:</strong> {{ object.ilosc_zamawiana }}</li>
              
              {% if object.id_dostawy %}
                <a class="list-group-item list-group-item-action" href="{% url 'app:delivered-items-detail' object.id_dostawy.id %}"><strong>Delivery:</strong> {{ object.id_dostawy }}</a>
              {% else %}
                <li class="list-group-item"><strong>Delivery:</strong> Deleted</li>
              {% endif %}
              
              <a class="list-group-item list-group-item-action" href="{% url 'app:order-detail' object.numer_zamowienia.numer %}"><strong>Order:</strong> #{{ object.numer_zamowienia.numer }}</a>
            </ul>
        </div>
        <br>
    </div>
{% endblock %}

project/app/templates/app/iteminorder_report.html
{% extends "base.html" %}

{% block content%}

  <div style="width: 100%; margin-left: 2%;">
    {% include "report_list.html" %}
    <div style="width: 75%; margin-left: 21%;">
        <h2>Items in Orders</h2>
        <br>
        <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Quantity</th>
                <th scope="col">Order</th>
                <th scope="col">Delivery</th>
              </tr>
            </thead>
            <tbody>
              {% for obj in object_list %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{ obj.ilosc_zamawiana }}</td>
                  <td>#{{ obj.numer_zamowienia.numer }}</td>
                  <td>{{ obj.id_dostawy }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
    </div>
  </div>

{% endblock %}

project/app/templates/app/payment_detail.html
{% extends "base.html" %}

{% block content %}
    <div style="width: 90%; margin-left: 5%; font-size:1.2rem;">
        <div class="card" style="width: 80%; margin-left: 10%;">
            <div class="card-header">
              <a href="delete/" class="btn btn-danger" style="float: right; margin-top: 1%;"><span class="fa fa-trash"></span></a>
              <a href="update/" class="btn btn-primary" style="float: right; margin-right: 2%; margin-top: 1%;"><span class="fa fa-pencil"></span></a>
              <h1 class="card-title">{{ object }}</h1>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><strong>Date:</strong> {{ object.data }}</li>
              <li class="list-group-item"><strong>Amount:</strong> {{ object.kwota }}PLN</li>
              {% if object.numer_zamowienia %}
                <a class="list-group-item list-group-item-action" href="{% url 'app:order-detail' object.numer_zamowienia.numer %}"><strong>Order:</strong> #{{ object.numer_zamowienia.numer }}</a>
              {% else %}
                <li class="list-group-item"><strong>Order:</strong> Deleted</li>
              {% endif %}
            </ul>
        </div>
        <br>
    </div>
{% endblock %}

project/app/templates/app/product_detail.html
{% extends "base.html" %}

{% block content %}
  <div style="width: 90%; margin-left: 5%; font-size:1.2rem;">
    <div class="card" style="width: 80%; margin-left: 10%;">
        <div class="card-header">
          {% if delivered %}
            <span class="d-inline-block" tabindex="0" data-toggle="tooltip" title="Disabled: First, remove the deliveries below" style="float: right; margin-top: 1%;">
              <a href="#" class="btn btn-secondary" ><span class="fa fa-trash"></span></a>
            </span>
          {% else %}
            <a href="delete/" class="btn btn-danger" style="float: right; margin-top: 1%;"><span class="fa fa-trash"></span></a>
          {% endif %}
          <a href="update/" class="btn btn-primary" style="float: right; margin-right: 2%; margin-top: 1%;"><span class="fa fa-pencil"></span></a>
          <h1 class="card-title">{{ object.nazwa }}</h1>
          <p class="card-text">{{ object.opis }}</p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><strong>Code:</strong> {{ object.kod }}</li>
          {% if object.id_kategorii %}
            <a class="list-group-item list-group-item-action" href="{% url 'app:category-detail' object.id_kategorii.id %}"><strong>Category:</strong> {{ object.id_kategorii }}</a>
          {% else %}
            <li class="list-group-item"><strong>Category:</strong> Deleted</li>
          {% endif %}
          {% if object.id_producenta %}
            <a class="list-group-item list-group-item-action" href="{% url 'app:producer-detail' object.id_producenta.id %}"><strong>Producer:</strong> {{ object.id_producenta }}</a>
          {% else %}
            <li class="list-group-item"><strong>Producer:</strong> Deleted</li>
          {% endif %}
        </ul>
    </div>
    
    {% if delivered %}
          <br>
          <div class="card" style="width: 80%; margin-left: 10%;">
            <div class="card-header">
              <h1 class="card-title">Connected Deliveries</h1>
            </div>
            <ul class="list-group list-group-flush">
              {% for delivery in delivered %}
                <a class="list-group-item list-group-item-action" href="{% url 'app:delivered-items-detail' delivery.id %}">{{ delivery }}</a>
              {% endfor %}
            </ul>
          </div>
    {% endif %}

    <br>
  </div>
{% endblock %}

project/app/templates/app/product_report.html
{% extends "base.html" %}

{% block content%}

  <div style="width: 100%; margin-left: 2%;">
    {% include "report_list.html" %}
    <div style="width: 75%; margin-left: 21%;">
        <h2>Products</h2>
        <br>
        <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Code</th>
                <th scope="col">Name</th>
                <th scope="col">Category</th>
                <th scope="col">Producer</th>
              </tr>
            </thead>
            <tbody>
              {% for obj in object_list %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td>{{ obj.kod }}</td>
                  <td>{{ obj.nazwa }}</td>
                  <td>{{ obj.id_kategorii }}</td>
                  <td>{{ obj.id_producenta }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
    </div>
  </div>

{% endblock %}