project/app/urls.py
from django.urls import path

from . import views


app_name = 'app'
urlpatterns = [
    # PRODUCTS
    path('products/', views.ProductListView.as_view(), name='product-list'),
    path('products/report/', views.ProductReportView.as_view(), name='product-report'),
    path('products/create/', views.ProductCreateView.as_view(), name='product-create'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('products/<int:pk>/update/', views.ProductUpdateView.as_view(), name='product-update'), 
    path('products/<int:pk>/delete/', views.ProductDeleteView.as_view(), name='product-delete'),

    path('products/wholesalers/', views.WholeSalerListView.as_view(), name='wholesaler-list'),
    path('products/wholesalers/report/', views.WholesalerReportView.as_view(), name='wholesaler-report'),
    path('products/wholesalers/create/', views.WholesalerCreateView.as_view(), name='wholesaler-create'),
    path('products/wholesalers/<int:pk>/', views.WholesalerDetailView.as_view(), name='wholesaler-detail'),
    path('products/wholesalers/<int:pk>/update/', views.WholesalerUpdateView.as_view(), name='wholesaler-update'),
    path('products/wholesalers/<int:pk>/delete/', views.WholesalerDeleteView.as_view(), name='wholesaler-delete'),

    path('products/producers/', views.ProducerListView.as_view(), name='producer-list'),
    path('products/producers/report/', views.ProducerReportView.as_view(), name='producer-report'),
    path('products/producers/create/', views.ProducerCreateView.as_view(), name='producer-create'),
    path('products/producers/<int:pk>/', views.ProducerDetailView.as_view(), name='producer-detail'),
    path('products/producers/<int:pk>/update/', views.ProducerUpdateView.as_view(), name='producer-update'),
    path('products/producers/<int:pk>/delete/', views.ProducerDeleteView.as_view(), name='producer-delete'),

    path('products/categories/', views.CategoryListView.as_view(), name='category-list'),
    path('products/categories/report/', views.CategoryReportView.as_view(), name='category-report'),
    path('products/categories/create/', views.CategoryCreateView.as_view(), name='category-create'),
    path('products/categories/<int:pk>/', views.CategoryDetailView.as_view(), name='category-detail'),
    path('products/categories/<int:pk>/update/', views.CategoryUpdateView.as_view(), name='category-update'),
    path('products/categories/<int:pk>/delete/', views.CategoryDeleteView.as_view(), name='category-delete'),

    path('products/delivered-items/', views.DeliveredItemsListView.as_view(), name='delivered-items-list'),
    path('products/delivered-items/report/', views.DeliveredItemsReportView.as_view(), name='delivered-items-report'),
    path('products/delivered-items/create/', views.DeliveredItemsCreateView.as_view(), name='delivered-items-create'),
    path('products/delivered-items/<int:pk>/', views.DeliveredItemsDetailView.as_view(), name='delivered-items-detail'),
    path('products/delivered-items/<int:pk>/update/', views.DeliveredItemsUpdateView.as_view(), name='delivered-items-update'),
    path('products/delivered-items/<int:pk>/delete/', views.DeliveredItemsDeleteView.as_view(), name='delivered-items-delete'),

    # ORDERS
    path('orders/', views.OrderListView.as_view(), name='order-list'),
    path('orders/report/', views.OrderReportView.as_view(), name='order-report'),
    path('orders/<int:pk>/', views.OrderDetailView.as_view(), name='order-detail'),
    path('orders/<int:pk>/update/', views.OrderUpdateView.as_view(), name='order-update'),
    path('orders/<int:pk>/delete/', views.OrderDeleteView.as_view(), name='order-delete'),
    path('orders/<int:pk>/add/', views.AddItemView.as_view(), name='order-additem'),
    path('orders/create/', views.OrderCreateView.as_view(), name='order-create'),

    path('orders/addresses/report/', views.AddressReportView.as_view(), name='address-report'),
    path('orders/addresses/<int:pk>/', views.AddressDetailView.as_view(), name='address-detail'),
    path('orders/addresses/<int:pk>/update/', views.AddressUpdateView.as_view(), name='address-update'),
    path('orders/addresses/<int:pk>/delete/', views.AddressDeleteView.as_view(), name='address-delete'),
    path('orders/addresses/create/', views.AddressCreateView.as_view(), name='address-create'),

    path('orders/items/', views.ItemInOrderListView.as_view(), name='items-list'),
    path('orders/items/report/', views.ItemInOrderReportView.as_view(), name='items-report'),
    path('orders/items/<int:pk>/', views.ItemInOrderDetailView.as_view(), name='items-detail'),
    path('orders/items/<int:pk>/update/', views.ItemInOrderUpdateView.as_view(), name='items-update'),
    path('orders/items/<int:pk>/delete/', views.ItemInOrderDeleteView.as_view(), name='items-delete'),
    path('orders/items/create/', views.ItemInOrderCreateView.as_view(), name='items-create'),

    path('orders/payments/', views.PaymentListView.as_view(), name='payment-list'),
    path('orders/payments/report/', views.PaymentReportView.as_view(), name='payment-report'),
    path('orders/payments/<int:pk>/', views.PaymentDetailView.as_view(), name='payment-detail'),
    path('orders/payments/<int:pk>/update/', views.PaymentUpdateView.as_view(), name='payment-update'),
    path('orders/payments/<int:pk>/delete/', views.PaymentDeleteView.as_view(), name='payment-delete'),
    path('orders/payments/create/', views.PaymentCreateView.as_view(), name='payment-create'),

    # EMPLOYEES
    path('employees/', views.EmployeeListView.as_view(), name='employee-list'),
    path('employees/report/', views.EmployeeReportView.as_view(), name='employee-report'),
    path('employees/<int:pk>/', views.EmployeeDetailView.as_view(), name='employee-detail'),
    path('employees/<int:pk>/update/', views.EmployeeUpdateView.as_view(), name='employee-update'),
    path('employees/<int:pk>/delete/', views.EmployeeDeleteView.as_view(), name='employee-delete'),
    path('employees/create/', views.EmployeeCreateView.as_view(), name='employee-create'),

    path('employees/positions/', views.PositionListView.as_view(), name='position-list'),
    path('employees/positions/report/', views.PositionReportView.as_view(), name='position-report'),
    path('employees/positions/create/', views.PositionCreateView.as_view(), name='position-create'),
    path('employees/positions/<int:pk>/', views.PositionDetailView.as_view(), name='position-detail'),
    path('employees/positions/<int:pk>/update/', views.PositionUpdateView.as_view(), name='position-update'),
    path('employees/positions/<int:pk>/delete/', views.PositionDeleteView.as_view(), name='position-delete'),

    # CLIENTS
    path('clients/', views.ClientListView.as_view(), name='client-list'),
    path('clients/report/', views.ClientReportView.as_view(), name='client-report'),
    path('clients/<int:pk>/', views.ClientDetailView.as_view(), name='client-detail'),
    path('clients/<int:pk>/update/', views.ClientUpdateView.as_view(), name='client-update'),
    path('clients/<int:pk>/delete/', views.ClientDeleteView.as_view(), name='client-delete'),
    path('clients/create/', views.ClientCreateView.as_view(), name='client-create'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import include, path

from .settings import DEBUG
from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='homepage'),
    path('about/', views.AboutPageView.as_view(), name='aboutpage'),
    path('report/', views.ReportPageView.as_view(), name='reportpage'),
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
]

if not DEBUG:
    handler400 = 'project.views.error404Handler'
    handler404 = 'project.views.error404Handler'
    handler500 = 'project.views.error500Handler'

project/templates/about.html
{% extends "base.html" %}

{% block content%}
    <div style="width: 90%; margin-left: 5%">
        <div class="card text-center">
            <div class="card-header">
                <ul class="nav nav-tabs card-header-tabs" id="myTab" role="tablist">
                    <li class="nav-item" role="presentation">
                        <a class="nav-link active" id="products-tab" data-toggle="tab" href="#products" role="tab" aria-controls="products" aria-selected="true">Products</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link" id="orders-tab" data-toggle="tab" href="#orders" role="tab" aria-controls="orders" aria-selected="false">Orders</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link" id="employees-tab" data-toggle="tab" href="#employees" role="tab" aria-controls="employees" aria-selected="false">Employees</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link" id="clients-tab" data-toggle="tab" href="#clients" role="tab" aria-controls="clients" aria-selected="false">Clients</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link" id="clients-tab" data-toggle="tab" href="#report" role="tab" aria-controls="report" aria-selected="false">Report</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link" id="authors-tab" data-toggle="tab" href="#guide" role="tab" aria-controls="guide" aria-selected="false">Use Guide</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link" id="authors-tab" data-toggle="tab" href="#authors" role="tab" aria-controls="authors" aria-selected="false">Authors</a>
                    </li>
                </ul>
            </div>
            <div class="tab-content card-body" id="myTabContent">
                <div class="tab-pane fade show active" id="products" role="tabpanel" aria-labelledby="products-tab">
                    <h3 class="card-title">Products Component</h3>
                    <p class="card-text" style="font-size: 1.15rem;">Contains and allows you to define new information about wholesalers, producers, categories, products and deliveries.</p><br>
                    <img src="https://cdn-bocdd.nitrocdn.com/HVBjtMJNipoZqehbxISQmnReBemWYQfv/assets/static/optimized/rev-7a2abc7/wp-content/uploads/2017/05/alternative-app-store.gif" alt="this slowpoke moves"  width="30%" />
                    <h3 class="card-title">Usage</h3>
                    <p class="card-text" style="font-size: 1.15rem;">It allows you to view, add, edit and delete information about the above-mentioned topics.</p>
                    <img src="https://i.gifer.com/origin/ae/aea3019ba3e50cf0b10006bf75c51e52_w200.gif" alt="this slowpoke moves"  width="15%" />
                </div>

                <div class="tab-pane fade" id="orders" role="tabpanel" aria-labelledby="orders-tab">
                    <h3 class="card-title">Orders Component</h3>
                    <p class="card-text" style="font-size: 1.15rem;">Contains and allows you to define new information about orders, items in orders, addresses and payments.</p><br>
                    <img src="https://cdn.dribbble.com/users/19479/screenshots/5116866/shipping_small-drib.gif" alt="this slowpoke moves"  width="30%" />
                    <h3 class="card-title">Usage</h3>
                    <p class="card-text" style="font-size: 1.15rem;">It allows you to view, add, edit and delete information about the above-mentioned topics. To view and edit all addresses go to Report component.</p>
                    <img src="https://i.gifer.com/origin/ae/aea3019ba3e50cf0b10006bf75c51e52_w200.gif" alt="this slowpoke moves"  width="15%" />
                </div>

                <div class="tab-pane fade" id="employees" role="tabpanel" aria-labelledby="employees-tab">
                    <h3 class="card-title">Employees Component</h3>
                    <p class="card-text" style="font-size: 1.15rem;">Contains and allows you to define new information about employees and their positions.</p>
                    <img src="https://cdn.dribbble.com/users/1453459/screenshots/4312772/media/ce6e6ea1db77ca363aec1c192749b214.gif" alt="this slowpoke moves"  width="30%" /><br><br>
                    <h3 class="card-title">Usage</h3>
                    <p class="card-text" style="font-size: 1.15rem;">It allows you to view, add, edit and delete information about the above-mentioned topics.</p>
                    <img src="https://i.gifer.com/origin/ae/aea3019ba3e50cf0b10006bf75c51e52_w200.gif" alt="this slowpoke moves"  width="15%" />
                </div>
                
                <div class="tab-pane fade" id="clients" role="tabpanel" aria-labelledby="clients-tab">
                    <h3 class="card-title">Clients Component</h3>
                    <p class="card-text" style="font-size: 1.15rem;">Contains and allows you to define new information about clients.</p><br>
                    <img src="https://ecommerce-platforms.com/wp-content/uploads/2018/05/mark-and-john-1549634879.gif" alt="this slowpoke moves"  width="30%" />
                    <h3 class="card-title">Usage</h3>
                    <p class="card-text" style="font-size: 1.15rem;">It allows you to view, add, edit and delete information about the above-mentioned topics.</p>
                    <img src="https://i.gifer.com/origin/ae/aea3019ba3e50cf0b10006bf75c51e52_w200.gif" alt="this slowpoke moves"  width="15%" />
                </div>

                <div class="tab-pane fade" id="report" role="tabpanel" aria-labelledby="report-tab">
                    <h3 class="card-title">Report Component</h3>
                    <p class="card-text" style="font-size: 1.15rem;">Contains and allows you to view compressed information about everything in your store.</p><br>
                    <img src="https://i.pinimg.com/originals/da/c7/13/dac71367c46f3f6cb5fb3cefbe305917.gif" alt="this slowpoke moves"  width="28%" /><br><br>
                    <h3 class="card-title">Usage</h3>
                    <p class="card-text" style="font-size: 1.15rem;">It allows you to view tables containing compressed information (without descriptions and comments) about your store. You can edit Addresses by clicking on them.</p>
                    <img src="https://i.gifer.com/origin/ae/aea3019ba3e50cf0b10006bf75c51e52_w200.gif" alt="this slowpoke moves"  width="15%" />
                </div>

                <div class="tab-pane fade" id="guide" role="tabpanel" aria-labelledby="guide-tab">
                    <h3 class="card-title">Use Guide</h3>
                    <img src="https://scoolspro.com/media/gallery/userguide.gif" alt="this slowpoke moves"  width="28%" />
                    <p class="card-text" style="font-size: 1.05rem;">To <strong>add</strong> the new object go to their section in their component and click the <button class="btn btn-success btn-sm"><span class="fa fa-plus"></span></button> button <br>which is located next to the searchbar at the top of the list.</p><br>
                    <p class="card-text" style="font-size: 1.05rem;">To <strong>edit</strong> the object go to their section in their component and click on it. Each detail view is equipped with the edit button <button class="btn btn-primary btn-sm"><span class="fa fa-pencil"></span></button><br>which is located at the top right corner of the detail page.</p><br>
                    <p class="card-text" style="font-size: 1.05rem;">To <strong>delete</strong> the object go to their section in their component and click on it. Each detail view is equipped with the delete button <button class="btn btn-danger btn-sm"><span class="fa fa-trash"></span></button><br>which is located at the top right corner of the detail page.<br>If <strong>an object is connected with another object</strong> for example a Product in Category - deletion (of the Category) is <strong>prohibited</strong> <button class="btn btn-secondary btn-sm"><span class="fa fa-trash"></span></button></p><br>
                    <p class="card-text" style="font-size: 1.05rem;">To <strong>add an item</strong> to order that already exists go to their detail view. Each order detail view is equipped with the button <button class="btn btn-success btn-sm">Add item <span class="fa fa-plus"></span></button><br>which is located at the top right corner of the detail page.</p>
                    
                </div>
                
                <div class="tab-pane fade" id="authors" role="tabpanel" aria-labelledby="authors-tab">
                    <h3 class="card-title">General info</h3>
                    <p class="card-text" style="font-size: 1.15rem;">The application is used to manage the store. This system will enable the storage of information about products, their stock in the warehouse, orders from customers, information about customers, employees and wholesalers from which the store orders the goods. The user who uses the application will be able to define, view and edit this data. For example, it can enter information about new orders, products, and also change, for example, employee wages.</p>

                    <img src="https://nazrulhoque.com/wp-content/uploads/2020/10/Boss-Designer.gif" alt="this slowpoke moves"  width="32%" />
                    <br>
                    <h3 class="card-title">Authors of the project</h3>
                    <p class="card-text" style="font-size: 1.15rem;"><a href="https://github.com/Endrju00">Andrzej Kapczyński</a> & <a href="https://github.com/kaczmaro">Jakub Kaczmarek</a></p>
                    <br><br>
                </div>
            </div>
        </div><br>
    </div>
{% endblock %}

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shop Manager</title>

    <!-- BOOTSTRAP -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

    <!-- ICONS FA FA -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

</head>
<body style="overflow-y: auto;">
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <div class="container-fluid" style="width: 80%; margin-left: 10;">
            <a class="navbar-brand" href="{% url 'homepage' %}">Shop Manager</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link" href="{% url 'homepage' %}">Home <span class="sr-only">(current)</span></a>
                <a class="nav-link" href="{% url 'app:product-list' %}">Products</a>
                <a class="nav-link" href="{% url 'app:order-list' %}">Orders</a>
                <a class="nav-link" href="{% url 'app:employee-list' %}">Employees</a>
                <a class="nav-link" href="{% url 'app:client-list' %}">Clients</a>
                <a class="nav-link" href="{% url 'reportpage' %}">Report</a>
            </div>
            </div>
        </div>
    </nav><br><br>
    
    <div class="content" style="width: 80%; margin-left: 10%;"><br><br>
        <div style="width: 100%">

            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <div class="position-fixed bottom-0 right-0 p-3" style="z-index: 5; right: 0; bottom: 0;">
                            <div id="liveToast" class="toast" data-autohide="false" role="alert" aria-live="assertive" aria-atomic="true" data-delay="2000">
                                <div class="toast-header">
                                    <img src="https://cdn-icons-png.flaticon.com/512/3361/3361382.png" class="rounded mr-2" alt="..." width="20" height="20">
                                    <strong class="mr-auto">Assistant</strong>
                                    <small>A second ago.</small>
                                    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="toast-body">
                                    {{ message }}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </ul>
            {% endif %}

            <script>
                $(document).ready(function() {
                    $(".toast").toast('show');
                });
            </script>

            {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>

project/templates/client_list.html
{% extends "base.html" %}

{% block content%}
    <div style="width: 90%; margin-left: 5%;">
        <div class="position-fixed card" style="width: 18rem;">
            <div class="card-header">
              Select topic
            </div>
            <ul class="list-group list-group-flush">
                <a class="list-group-item list-group-item-action" href="{% url 'clients:client-list' %}">Clients</a>
            </ul>
        </div>

        {% include "list.html" %}
        
    </div>
{% endblock %}

project/templates/create_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="jumbotron" style="width: 70%; margin-left: 15%; font-size:1.2rem;">
        <h3 class="display-4">Let's create something new...</h3>
        <br>
        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <br>
            <input class='btn btn-primary btn-lg' type="submit" value="Create!" style="width: 100%;">
        </form>
    </div>
{% endblock %}

project/templates/delete_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="jumbotron" style="width: 70%; margin-left: 15%; font-size:1.2rem;">
        <h3 class="display-4">Warning!</h3>
        <br>
        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <h4 class="font-weight-light">Are you trying to delete object named "{{ object }}"?</h4>
            <input class='btn btn-danger btn-lg' type="submit" value="Yes, I want to do it." style="width: 100%;">
        </form>
    </div>
{% endblock %}

project/templates/employee_list.html
{% extends "base.html" %}

{% block content%}
    <div style="width: 90%; margin-left: 5%;">
        <div class="position-fixed card" style="width: 18rem;">
            <div class="card-header">
              Select topic
            </div>
            <ul class="list-group list-group-flush">
                <a class="list-group-item list-group-item-action" href="{% url 'employees:employee-list' %}">Employees</a>
                <a class="list-group-item list-group-item-action" href="{% url 'employees:position-list' %}">Positions</a>
            </ul>
        </div>

        {% include "list.html" %}
        
    </div>
{% endblock %}

project/templates/error.html
{% extends "base.html" %}
{% block content%}

    <div class="jumbotron" style="width: 90%; margin-left: 5%;">
        <h1 class="display-4">Oops... Something went wrong :( 
        </h1>
        {% if code == 404 %}
            <p class="lead">Not found what you are looking for, please make sure you are using the app correctly. Error code {{code}}</p>
        {% elif code == 500 %}
            <p class="lead">Something you are trying to do is prohibited... Error code {{code}}<br><br>
                <strong>Probable reasons are: </strong> 
                <ul> 
                    <li>You are trying to illegally delete an object connected with another object(s). <br><strong>Solution:</strong> Delete object that do not include another object in the form at first. <strong>For example</strong> firstly delete a Product and then the Producer.</li>
                </ul>
            </p>
        {% else %}
            <p class="lead">Please make sure you are using the app correctly.</p>
        {% endif %}
        <hr class="my-4">
        <p>To see each component and learn how it works, click the button below.</p>
        <a class="btn btn-primary btn-lg" href="{% url 'aboutpage' %}" role="button">Learn more</a>
    </div>
{% endblock %}

project/templates/home.html
{% extends "base.html" %}

{% block content %}
    <div class="jumbotron" style="width: 90%; margin-left: 5%;">
        <h1 class="display-4">Welcome to Shop Manager!</h1>
        <p class="lead">The application is equipped with several components related to products, orders, employees and customers of your store.</p>
        <hr class="my-4">
        <p>To see each component and learn how it works, click the button below.</p>
        <a class="btn btn-primary btn-lg" href="{% url 'aboutpage' %}" role="button">Learn more</a>
    </div>
    <div style="width: 90%; margin-left: 5%; text-align: center;">
        <img src="https://cdn.dribbble.com/users/812639/screenshots/6486869/shooping_1-800x600.gif" alt="this slowpoke moves"  width=25% />
    </div>
    
{% endblock %}

project/templates/list.html
<div class="card" style="width: 75%; margin-left: 25%;">
    <ul class="list-group list-group-flush">
        <div class="card-header">
            
            {% if results %}
                <h3>{{ name }}</h3>
                <h4 class="font-weight-light" style="float: left; margin-bottom: 0;">{{ results }}</h4>
            {% else %}
                <h3 style="float:left; margin-bottom: 0;">{{ name }}</h3>
            {% endif %}
            <form method="post">{% csrf_token %}
                <div class="input-group mb-3" style="width: 45%; height:20%; float:right;">
                    <input type="text" class="form-control btn-sm" placeholder="{{ search }}" aria-label="Recipient's username" aria-describedby="button-addon2" style="width: 70%; float: left;" name="search" maxlength="20">
                    <button class="btn btn-outline-secondary btn-sm" type="submit" id="button-addon2" style="float: right;"><span class="fa fa-search"></span></button>
                    <a href="create/" class="btn btn-sm btn-success" style="float: right; margin-left: 2%;"><span class="fa fa-plus" style="margin-top: 7px;"></span></a>
                </div>
            </form>
          </div>
        {% for obj in object_list %}
            {% if obj.numer %}
                <a class="list-group-item list-group-item-action" href="{{ obj.numer }}">{{ obj }}</a>
            {% else %}
                <a class="list-group-item list-group-item-action" href="{{ obj.id }}">{{ obj }}</a>
            {% endif %}
        {% endfor %}
    </ul>
</div>
<nav aria-label="Page navigation example" style="width: 55%; margin-left: 25%; margin-top:2%;">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}
        <li class="page-item"><span class="page-link">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span></li>
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
        {% endif %}
    </ul>
</nav>

project/templates/report_list.html
<div class="position-fixed card" style="width: 15%; font-size: 0.8rem;">
    <ul class="list-group list-group-flush">
        <a class="list-group-item list-group-item-action" href="{% url 'app:wholesaler-report'%}">Wholesalers</a>
        <a class="list-group-item list-group-item-action" href="{% url 'app:producer-report'%}">Producers</a>
        <a class="list-group-item list-group-item-action" href="{% url 'app:category-report'%}">Categories</a>
        <a class="list-group-item list-group-item-action" href="{% url 'app:product-report'%}">Products</a>
        <a class="list-group-item list-group-item-action" href="{% url 'app:delivered-items-report'%}">Delivered Items</a>
        <a class="list-group-item list-group-item-action" href="{% url 'app:address-report'%}">Addresses</a>
        <a class="list-group-item list-group-item-action" href="{% url 'app:order-report'%}">Orders</a>
        <a class="list-group-item list-group-item-action" href="{% url 'app:items-report'%}">Items in Orders</a>
        <a class="list-group-item list-group-item-action" href="{% url 'app:payment-report'%}">Payments</a>
        <a class="list-group-item list-group-item-action" href="{% url 'app:employee-report' %}">Employees</a>
        <a class="list-group-item list-group-item-action" href="{% url 'app:position-report' %}">Positions</a>
        <a class="list-group-item list-group-item-action" href="{% url 'app:client-report' %}">Clients</a>
    </ul>
</div>